"""Add conversation model for chat history

Revision ID: 9a3bc9d7e4b7
Revises: 
Create Date: 2025-09-04 19:14:48.725215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3bc9d7e4b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=True),
    sa.Column('analysis_data', sa.JSON(), nullable=True),
    sa.Column('metrics_involved', sa.JSON(), nullable=True),
    sa.Column('is_follow_up', sa.Boolean(), nullable=True),
    sa.Column('parent_conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('session_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('idx_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index('idx_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_user_session', ['user_id', 'session_id'], unique=False)

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uniq_user_metric_ts'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uniq_user_metric_ts'), ['user_id', 'metric_type', 'timestamp'], unique=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_user_session')
        batch_op.drop_index('idx_user_created')
        batch_op.drop_index('idx_session_created')

    op.drop_table('conversations')
    # ### end Alembic commands ###
